### ISSUE TITLE
n installs faulty OSX node

### ISSUE THREAD

**Issue by Morriz** [tj/n#124]
I suspect the compilation is faulty, since I get this error after 'n -latest' (or 'n -prev', which is strange):

$ node
Illegal instruction: 4

I now have to download node again for my OSX 10.8.4 ;(

**Comment by KrekkieD** [comment]
I agree with @anthonyettinger about no sudo requirement. If the package has a typo and removes / instead of ./ I need to make overtime, so to say. :)

**Comment by maxrimue** [comment]
Leaving out `sudo` would mean that n couldn't install Node.js globally, unless you give your user account write permissions for `/usr/local`. If you want to establish a local installation of Node.js, all you need to do is to change the N_PREFIX in line 10 of the bash script to any path inside your account directory, then n installs the Node.js versions into there, however, they won't be installed globally, so you won't be able to access Node.js simply via `node` on the command line, which means that you'll have to call the desired Node.js version with its absolute path. Beside that, I don't really see why using/installing n or Node.js globally should be a problem?

**Comment by KrekkieD** [comment]
The global install is not an issue. It is very much possible to install npm modules globally without sudo, and for safety that is the preferred way. Sudo gives a lot of power, like I said if the package does a file deletion it could accidentally be deleting system files with the power of sudo.

I see your point though with copying to the protected directory. I tried the copy command using sudo (something like `$ sudo n 0.10`) which appears to work, but new to `n` so don't know how to use it from there.

**Comment by maxrimue** [comment]
@KrekkieD 
>The global install is not an issue. It is very much possible to install npm modules globally without sudo, and for safety that is the preferred way.

AFAIK npm just gives write permissions for its `node_modules` folder, which is why you can modify it without root rights. If this is what you want, give yourself write permissions for `usr/local/n` and n should work without root rights.

>Sudo gives a lot of power, like I said if the package does a file deletion it could accidentally be deleting system files with the power of sudo.

Yeah, but that's very unlikely to happen. It's defined in the bash file where the commands happen, and as long as you don't change the bash, and we don't pass a destructive PR without looking at the code, that won't happen.

>I see your point though with copying to the protected directory. I tried the copy command using sudo (something like $ sudo n 0.10) which appears to work, but new to n so don't know how to use it from there.

A local installation of both n and Node.js works this way:
Clone n into your home directory, change the bash as mentioned above, then call n directly (e.g. `./n/bin/n <command>`), and the Node.js versions should be within the folder you wrote in the bash file. You then have to call these Node.js binaries directly again, since they're not global.

**Comment by tedgaydos** [comment]
If you don't want to give sudo to users, you can always let the user install node locally via `n`. I just installed `n` on a machine globally using `npm install -g n` to a node/npm install under /usr. I then did an `export N_PREFIX=$HOME` and ran `n 0.10` without any access denied to /usr/... errors. You can also ensure that protected system files are not deleted when using `n rm` as it will be removing installs from the user's home directory. The only thing I noticed that was odd was I needed to refresh my shell to make the local ndoe installed in my home directory to take over.

**Comment by qw3rtman** [comment]
Is this still an issue or can this be closed?

**Comment by troy0820** [comment]
I'm closing this issue.
