### ISSUE TITLE
support any semver value for install or use

### ISSUE THREAD

**Issue by tjwebb** [tj/n#192]
Being able to, for example, use `n` to support automatic compatibility with any `engines.node` version in a package.json would be amazing. e.g.

```
$ n 0.10.x
$ n ">=0.10.0 <= 0.10.28"
```

Would be more convincing for programmatic-type usage, i.e. with [n-api](https://github.com/tjwebb/n-api) or similar:

``` js
var n = require('n-api');
n.use(pkg.engines.node, 'index.js');
```

**Comment by tedgaydos** [comment]
I am going to assume that you would want n to install the latest of the wildcard version similar to the way npm installs from package.json? If so, I would like to give this a shot.

**Comment by bitdivine** [comment]
+1.  This is exactly what I had in mind.  Happy to help if needed.

**Comment by bitdivine** [comment]
Thoughts on how this might be used in practice, especially on the context of package.json:
Note: On the command line, wherever one can use, say "latest" as the version of node, one might use "engine":

    n use engine ./server.js

Note: I know of no way of making npm use a specific version of node apart from putting that node at the front of the path.  That one can do, with PATH="$(dirname "$(bin 5.0.0)")" npm install.  We might make this easy:

    n with <version> npm install

or, shorter but less general:

    n npm <version> install

Here are implementations to play with:  
 * fork: https://github.com/bitdivine/n
 * code: https://github.com/bitdivine/n/commit/215c100a227fc19258901caad3e67a10732b3bf3

**Comment by bitdivine** [comment]
Note: The sketch implementation uses the node modules `semver` and `n-api`.  Of those, `semver` is what npm uses for its semantic versioning, so if npm is installed on a machine, so is semver.  It doesn't add a new dependency and using the same code to do the comparison ensures that we always get the same answers.  However `n-api` is _not_ included in `n` or `npm`, so that dependency should probably be eliminated.  The shell functions in n itself should be able to provide the n-api. ;-)

Note: Installing a new version with `n engine` will require a different logic from the one in the sketch.  `semantic_version()` looks for a compatible version amongst all the installed versions.  This needs another function that finds a compatible version among all versions that exist.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
