### ISSUE TITLE
specific node versions for specific folders/projects

### ISSUE THREAD

**Issue by Globegitter** [tj/n#204]
It would be great if I could specific specific node versions being used in specific paths (and all subfolders).
The use-case is, that for some of my projects I can already use 0.11.x, where-as for some I have to use 0.10.x and constantly switching is a bit tedious and error-prone.

**Comment by Globegitter** [comment]
@tjwebb I just had some time to briefly look into nex-engines. It is basically running `n <version>` (so changing the node version globally) and then turning it back to the old version, right? Just asking to make sure I understand it correctly.

**Comment by tjwebb** [comment]
Basically, yea

**Comment by wbyoung** [comment]
@Globegitter is [`avn`](https://github.com/wbyoung/avn) similar to what you're looking for where it will automatically switch your node version when you `cd` into a directory?

**Comment by mciparelli** [comment]
+1 to this, would be a nice to have feature

**Comment by quidmonkey** [comment]
Another +1. This would be crucial to us using n in our dev environment.

**Comment by Meekohi** [comment]
This would be awesome. I very often cd into a directory that expects an older version of node, and I don't always realize I'm on the wrong version until putzing around for a bit.

**Comment by wbyoung** [comment]
@Meekohi I'd encourage you to give [`avn`](https://github.com/wbyoung/avn) a shot.

After developing a better understanding of both `n` as well as automatic version switching as is done via tools like `autoenv` and `rvm`, I don't think that this is something that should ever work its way in to `n` and should instead remain the job of a dedicated tool that either integrates directly with `n` (like `avn`) or something that can simply execute arbitrary commands upon changing directories (like `autoenv`).

Asking the authors of `n` to also maintain functionality that's present in various other tools seems like a waste of effort.

To those who have commented on here and to the original requestor:

1. Is there anything that `autoenv` or `avn` can't solve that would necessitate this functionality actually being a core part of `n`?
2. Would simply updating `n`'s `README` to point to tools for automatic changing when changing directories be sufficient enough to close this issue?

Finally, the architecture of `n` where it actually replaces the installation of `node` within `/usr/local/bin` (or wherever) actually makes it somewhat "dangerous" to make these changes automatically when switching directories. It's easy to forget that a change has been made and leave your installation on a different version after using a specific project.

**Comment by Meekohi** [comment]
Thanks for the pointer to `avn`. I now understand one major issue here is that unlike `nvm` which switches your node version primarily by adjusting your path, `n` is swapping out the system version. That makes it a little unclear what it means to choose a version based on your directory (since it is really just the last directory that you enter from any terminal).
A pointer to `avn` in the documentation would definitely be helpful. I have been using it for a day now and it is definitely helpful as long as you understand the limitations.

**Comment by wertlex** [comment]
+1. n looks very cool, but config-based usage required.

**Comment by shadowspawn** [comment]
Good comments on why switching when `cd` is not a good match for `n`, and other approaches.

This issue has not had much activity in years. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
