### ISSUE TITLE
NPM not working after I installed nvm n and now I keep getting “dyld: bad external relocation length”

### ISSUE THREAD

**Issue by anwaukoni** [tj/n#244]
I installed nvm, n, using sudo and decided to test it out by downloading several versions of node on my system. When I tried to switch between the node versions I kept getting "Permissions denied." So I decided to sudo the command for switching between versions too. That's when all hell broke loose. I keep getting

     dyld:bad external relocation length
I've tried to reboot my terminal with some hope that it would magically fix itself out. Alas, I was wrong.Thanks in Advance.

Update 1: I've tried to use npm to install yo and it gives me the same "dyld" prompt, along with the following:

      Trace/BPT trap: 5
Essentially I can't use npm anymore.

**Comment by altern8tif** [comment]
What I understand is you can't use `n` and `nvm` at the same time due to conflicts.  [This] (http://www.mattpalmerlee.com/2013/03/23/installing-and-switching-between-multiple-versions-of-node-js-n-vs-nvm/) is a bit dated but I suppose the solution could still be relevant.

>__Can I use both n and nvm?__
Sure, but you might not want to use both at the same time since they will conflict. If you want to disable nvm just comment out the line that sources the script file from your .profile or .bashrc file:
[[ -s ~/.nvm/nvm.sh" ]] && . ~/.nvm/nvm.sh
and then run:
source .profile
to remove the nvm script from your path.

**Comment by tjwebb** [comment]
Yea, using n and nvm at the same time is a recipe for disaster. They solve the version-switching problem in very different ways. I don't think either n or nvm can be blamed for this -- the best solution is to just need to pick one and stick with it.

**Comment by anwaukoni** [comment]
No, I'm not using them both at the same time. I just downloaded n and was only using that. When I tried to sudo change my version of node, it basically broke n and npm (and who knows what else?). 

I don't mind deleting n, but npm is broken and I dont know what to do about that. Whenever I want to use either of these programs I get the "dyld" and "trace" prompt. 

Do you suggest I delete npm and re-install?

**Comment by anwaukoni** [comment]
I basically broke my node installation. The error messages apparently don't come from npm but from osx. I uninstalled npm, node, and n, then reinstalled using nvm. All is working now.
