### ISSUE TITLE
"n use" and "n bin" should work with partial version numbers

### ISSUE THREAD

**Issue by callumlocke** [tj/n#252]
To install the latest `0.10.*` version, you can just do `$ n 0.10`. You don't need to know the latest patch number.

But if you try to do `$ n use 0.10 ...` or `n bin 0.10`, it says `Error: 0.10 is not installed`, even if you have several `0.10.*` versions installed.

It would be cool if `n use` and `n bin` could just figure out the highest installed matching version, and use that.

**Comment by tedgaydos** [comment]
I am looking into doing something like this. See #192.

**Comment by JohnRGee** [comment]
I wonder if is better to use the highest already installed version, or to look up the latest version number on mirror? The latest installed version would save a lookup and avoids failing if local is not latest, but the mirror version is more consistent with install, and how codenames (like `lts`) behave with `bin` and `use`.

Either would be a convenience.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report. Although I do like the idea, and likely to do it at some point anyway!

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
