### ISSUE TITLE
Invalid version on Raspberry Pi 2

### ISSUE THREAD

**Issue by tjallingt** [tj/n#274]
I installed node v0.12.0 and npm from http://node-arm.herokuapp.com/
When I tried upgrading to the latest version with n (now v0.12.1) I got the error ```invalid version v0.12.1```.
Also when I use ```n ls``` it tells me that I don't have a version of node installed, perhaps this is related.
What can/should I do to make this work?

**Comment by maxrimue** [comment]
Currently, there is no official version of Node.js 0.12.x for ARMv7, the kind off chip your RasPi 2 has, the Node.js you installed is an unofficial build from an unofficial source. `n` only uses the official sources, and since there is no official build for ARMv7, there is nothing that `n` could download on your device.
What you could do is:
1. Use io.js instead, it provides the right builds for you in its official source (also works in n with `n io latest`), or
2. Search for a source that provides the right builds, so for ARMv7, and change line 20 of `bin/n`,       `${IO_MIRROR-https://iojs.org/dist/})` to whatever URL your source has

I've heard that Node.js will soon provide ARMv7 builds again when they upgrade to a new V8 version which simplifies building for ARMv7 or so.

The reason why `n` tells you that there's no Node is installed is because, as far as I know, you installed Node.js probably with a `.deb`, which doesn't install Node.js into the `n` directory, which is the place `n` looks for valid versions.

**Comment by tjallingt** [comment]
Clear, thanks!

Maybe the error should say something along the lines of ```no compatible distribution of version v0.12.1 found```, which is much more informative?

Ill just hope that I you are right and node will provide armv7 builds soon (and maybe in the meantime I will experiment with io.js).

**Comment by maxrimue** [comment]
Yes, you're right there, I'll have a look soon. By the way, I'm not sure if you can use io.js on your RasPi 2 with Raspbian Wheezy, it might be the case that, if you have wheezy, you have to upgrade to Jessie first, at least my friend has experienced that problem.
