### ISSUE TITLE
phantom.js support

### ISSUE THREAD

**Issue by EvanCarroll** [tj/n#278]
Phantom.js is node-ish, perhaps we should update to include it as a distro. It's essentially node.js with webkit baked in. It's used for headless testing and quite popular.

```text
Q: Why is PhantomJS not written as Node.js module?

A: The short answer: "No one can serve two masters."

A longer explanation is as follows.

As of now, it is technically very challenging to do so.

Every Node.js module is essentially "a slave" to the core of Node.js, i.e. "the master". In its current state, PhantomJS (and its included WebKit) needs to have the full control (in a synchronous matter) over everything: event loop, network stack, and JavaScript execution.

If the intention is just about using PhantomJS right from a script running within Node.js, such a "loose binding" can be achieved by launching a PhantomJS process and interact with it.
```

**Comment by maxrimue** [comment]
I think including support for PhantomJS would go way beyond what n was thought for.
I see two problems here:
1. It seems like there's no pre-built option for Linux available, and since n doesn't support building from source, and is also a bash script, it would only support OS X
2. PhantomJS might be similar to Node.js, but it's still something different. n was meant to be simple, only downloading and installing Node.js versions. The reason why we added io.js was just because io.js has a lot in common with Node.js, since it's just a fork

**Comment by tjwebb** [comment]
Yea `n` isn't designed to be a downloader/installer of node-like things. That's what npm does.
