### ISSUE TITLE
support for private node builds

### ISSUE THREAD

**Issue by pmuellr** [tj/n#293]
Currently `n` looks for `node` and `iojs` installs, by virtue of the `BINS` var intialization at https://github.com/tj/n/blob/master/bin/n#L17 .

I'd like to be able to install personal builds with a different name - think `mine` which would be a peer directory in `/usr/local/n/versions/`.  I don't care too much about the installation bits - that would be ... complicated.  So assume I'd handle laying down a node build in `/usr/local/n/versions/mine/X.Y.Z`.  I'm just looking for support for the activation bits.

Hacking `n` to add a `mine` entry to `BINS`, with a personal build laid down as described above, running `n` lists the installed personal build.  Seems to switch correctly.  YAY!

Wondering if there would be interest in adding support for this in the package, rather than editing the `n` script personally.  Basically, programmatically add additional entries to BINS that would be found along `/usr/local/n/versions`.

Happy to make an attempt at this, tho my bash-foo is weak, so pointers would be much appreciated.

**Comment by maxrimue** [comment]
My idea would be to add a `-c`/`--custom` flag, and then take the next parameter as a source of the custom build and take the next parameters for name and version of that custom build, so n will create a folder in `$N_PREFIX/versions/` with that name and inside that, a folder for the version that you passed, and then copy the custom Node into there. I'm not too sure how this idea would cooperate with the rest of the script, I'm unsure if custom folders would be supported automatically.

You could try implementing it by adding a flag like `-q` and `-d` at the end of the script, leading to a new function called something like `add_custom` while passing the next three parameters.

**Comment by pmuellr** [comment]
@maxrimue good idea for installing the custom build! thx

>  I'm not too sure how this idea would cooperate with the rest of the script, I'm unsure if custom folders would be supported automatically

This was my main concern - the `BINS` var (see link to source at top) needs to have the new custom version subdir name added to it - and then things seem to work fine.  I've already hacked my version with a `mine` subdir and new `mine` entry in `BINS`.  But I figure this can be calculated dynamically in the script, given some awesome bash foo, which I'm short on.

**Comment by maxrimue** [comment]
@pmuellr Well, I don't have time right now to try it with actual code, but I figured this out:
At the beginning of the script, n sets `BINS`, `BIN_NAME` and `VERSIONS_DIR`, I think those are the most important for a custom solution. n should search its `versions` folder for folders aside from `io` and `node` and take the others folders names, if existing, into the array.
This means: You run the `-c` command, n creates a new folder inside `versions` called the way you passed the command, like `-c mycustomnode` results in creating the folder `mycustomnode`. The next time you use n, it will add `mycustomnode` to the arrays because it found the folder, and that should be it.
You still need to consider all `curl` and `wget` commands though, it depends upon how you want to design the API, should the user just always type `-c path mycustomnode version` to add a new version, or should it somehow work automagically when you type `n mycustomnode 0.12.7` so that it searches in the path of the last time? However you do it, you will need to disable the `curl` and `wget` commands because n might try to download `mycustomnode` somewhere which obviously won't work.

**Comment by maxrimue** [comment]
@pmuellr Is this still a thing?

**Comment by pmuellr** [comment]
I'm still interested, if that's what you mean.  One of my co-workers ended up building a fork of `n` for just this purpose.  Let me send him here to see if there's anyway he could generalize the work.

**Comment by wblankenship** [comment]
I'll submit a PR later today with a version that does just that.

In addition to `node` and `io`, it adds a `project` tag which is controlled via environment variables. It also unbundles contstructing the `curl` and `wget` commands allowing you to pass extra stuff through like proxy configs and basic auth.

**Comment by maxrimue** [comment]
@wblankenship Sounds good, looking forward to it, thanks

**Comment by jamen** [comment]
This should be closed.  :o
