### ISSUE TITLE
Unable to update n

### ISSUE THREAD

**Issue by rslid** [tj/n#297]
Hello,

The update process is giving me hard time. Im not able to get the latest version, it seems that Im stuck with 0.10.38 Can you give me any advice how to proceed ? 

n stable

install : node-v0.12.7
mkdir : /usr/local/n/versions/node/0.12.7
fetch : https://nodejs.org/dist/v0.12.7/node-v0.12.7-linux-x64.tar.gz
installed : v0.10.38

**Comment by maxrimue** [comment]
Have you installed Node.js previously with something else than n? It seems like you installed Node.js with for example a package manager like `apt`, `homebrew` or similar.

**Comment by rslid** [comment]
Only with npm - is it possible this to be related ?

**Comment by maxrimue** [comment]
I don't mean n, I meant Node.js. Have you ever installed Node.js without using n?

**Comment by rslid** [comment]
Not really. I tried full removal even manually and all possible solutions which I found in google but without any success.

**Comment by maxrimue** [comment]
What does `which node` get you?

**Comment by apandichi** [comment]
I'm seeing the same issue in Fedora 22. And yes, Node.js was installed with Fedora's package manager  dnf (previously yum). Is there a workaround?

**Comment by maxrimue** [comment]
@apandichi If you really don't want to remove the Node.js with yum/dnf, you just need to make sure that whatever path your n installs Node.js to gets exported so that Node.js is globally available. I never ran into these kind of issues, n, as long as not modified, installs Node.js to `/usr/local/`, I don't know how your package manager handles installations, I guess that Fedora is overriding the global variable for Node.js to point to yum/dnf's installation, so if `export`-ing manually doesn't work, there's probably an override happening you need to stop, which is why I would simply remove the other Node.js if I was you.

**Comment by apandichi** [comment]
@maxrimue It looks like I have the following install path available: /usr/local/n/versions/node/0.12.7
I guess I could manually 'export PATH' in my bashrc/zshrc. Thanks!

**Comment by maxrimue** [comment]
@apandichi You could use this path, however, `/usr/local/n/versions/` is where n stores the version. As I said, you can use it, but if you for example install another version, Node.js will remain version 0.12.7. To use the path where n installs to, you should use `/usr/local/bin/node`, and whenever you install another version with n, that executable will change, too.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
