### ISSUE TITLE
"n project" command failed

### ISSUE THREAD

**Issue by vincentngthu** [tj/n#314]
We has a mirror: https://npm.taobao.org/mirrors/node/ and I use the "n project" command like this
```
PROJECT_NAME="node" PROJECT_URL="https://npm.taobao.org/mirrors/node/" n project latest
```
outputs
```
     install : node-v4.2.1

  Error: invalid version 4.2.1
```
Am I miss something?

**Comment by vincentngthu** [comment]
After digging into the src, I found this function produce the error
https://github.com/tj/n/blob/master/bin/n#L360

The download links of https://npm.taobao.org/mirrors/node/ is actually a 304 redirect, which the function can not handle. No matter what cmds are using(curl/wget).

**Comment by goorockey** [comment]
@vincentngthu Just comment [#L502](https://github.com/tj/n/blob/master/bin/n#L502) and then it works for me :)

**Comment by goorockey** [comment]
Is it better to change L362 to `$GET -Is $1 -sSf 2> /dev/null` ?

**Comment by curioussavage** [comment]
I also have this issue on raspbian.

**Comment by qw3rtman** [comment]
So `is_ok()` should check if the response is `302` (or some redirect) as well?

**Comment by vincentngthu** [comment]
@qw3rtman Yes, I think so. And the download logic should handle server redirection as well.

**Comment by CoderIvan** [comment]
`$GET` use `curl -L` to resolve the redirect problem.

This issue is the mirror of  `https://npm.taobao.org/mirrors/node` will return `206`, as follow:

![image](https://cloud.githubusercontent.com/assets/7960859/15883702/3cf4acf8-2d7d-11e6-8ad2-81d6d731b4f3.png)

So, change [L364](https://github.com/tj/n/blob/master/bin/n#L364) to `grep '2..'`, it will work well

**Comment by vincentngthu** [comment]
@CoderIvan 

> grep "200"

works for me
