### ISSUE TITLE
Cant uninstall n and node

### ISSUE THREAD

**Issue by krzysieki** [tj/n#327]
Hi

My system is Ubuntu 14.04LTS.
So I installed n with "sudo npm install -g n".

Next, I installed node 4.2.1 using n
N says now that 4.2.1 is the only node on my env.

What should I do to remove node and n? 

n rm 4.2.1 

results in 
"Error: cannot remove currently active version (node/4.2.1)"

PS
Thanks for your work!

**Comment by knotech** [comment]
I had to use `sudo n rm 4.2.0`. That worked for me on OSX yosemite. Does that solve it for you on Ubuntu?

**Comment by sunh3** [comment]
I am on Linux mint 17.2 and I have the same issue.

using sudo n rm does not help

**Comment by knotech** [comment]
Okay, so n will not uninstall the last version of node available to it.

I dealt with this in time-tight situation, but If I recall correctly when you install n it rewrites the paths to node from /usr/local/bin/node to (I think.. ) /opt/local/bin/ or some other directory. I did it in OSX.

On Ubuntu, it seems to be located in /usr/bin/node when I do an ```~$ ls -la `which node` ``` it's a symlink to ```/etc/alternatives/node``` 

What I did was go manually delete the new locations that n had created for node and npm. The package manager I used to install node originally couldn't find them, but I would type ```node -v``` and get some version number. So I Symlinked the original locations of node and npm back to /usr/local/bin/node (/usr/bin/node in your cases), to uninstall them with the package manager that I originally used to install them.

Then I followed the steps here http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

The paths are going to be different because it's Ubuntu, but the principal is the same. You're going to have to find and delete the remnants, like globally install modules, wherever they're stored, and then reinstall.

**Comment by knotech** [comment]
@sunh3 see https://github.com/tj/n/issues/328 if npm isn't broken you should be able to reset the prefix, to (I'm guessing here) probably had npm install orignally, and clean it up from there.

**Comment by krzysieki** [comment]
Thanks @knotech and I confirm that the manual steps above, from stackoverflow, worked. But still, I suppose there should be a way to uninstall all node versions installed with n. And now it seems that n does not allow to fully uninstall itself (with installed "nodes")

**Comment by knotech** [comment]
Yeah, that seemed to be the problem, the fact that node had been installed from a different source, and n borked the symlinks. I concur, there should be a way to uninstall it, I'm bummed I can't use it in production.

**Comment by pentool** [comment]
I've contacted the node team because I had the same issue. I am new to node/npm and somehow, apparently I installed node and from somewhere else I also got n installed. The node them was kind enough to point out that 'n' is the node version manager (I didn't even know that) and recommended to post my issue here.

Since I didn't know what 'n' is, I have followed all possible uninstall recommendation found on this page: https://docs.npmjs.com/misc/removing-npm but none of them uninstalled the node version found in the 'n' directory.

Since I wasn't sure what I'm facing with, I solved this problem by doing a clean install of my system :-) This actually took me less time (around 30 minutes) compared to how much time and frustration it took me to research this issue and still not founding a solution :-)

OS X El Crapitan 10.11.3

**Comment by monapasan** [comment]
Is there any workaround yet ?

**Comment by pentool** [comment]
As for me, I just did a clean install of my system. Hate having gunk I can't decently clean out.

**Comment by naktinis** [comment]
So it's impossible to fully uninstall `n`? I also get "Error: cannot remove currently active version". Am I missing something?

**Comment by troy0820** [comment]
@naktinis are you trying to uninstall n or a specific node version? It isn't going to let you uninstall a version that you are currently using.  If you want to uninstall global npm packages, use `npm unistall -g n`

**Comment by yun313350095** [comment]
@naktinis  npm uninstall -g n

**Comment by LeoCecilia** [comment]
you use the command to uninstall node
``` bash
cd /usr/local/n/versions/node && rm -rf 6.0.0
```

**Comment by dandv** [comment]
See #169 for workarounds. This issue was raised more than 4 years ago.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. 

I have opened a new issue with some research and ideas about what we might do in future. Subscribe to that issue for updates and/or give it a 👍 
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
`n uninstall` has been added in v4.1.0. It deletes node and npm from the install destination (`N_PREFIX` or `/usr/local`). It does not affect the cached downloaded versions.

**Comment by ollydixon** [comment]
@shadowspawn this compeltely breaks my system, even ```brew reinstall node@12``` emits ```-bash: node: command not found```

**Comment by shadowspawn** [comment]
@ollydixon 
Try a new shell (or Terminal window). Maybe the old location is still in the cache.

Otherwise in very general terms, node is found by being installed somewhere on your hard drive, and that location being in your shell `PATH`.

```sh
echo $PATH
command -v node
```

**Comment by bngbog** [comment]
Seriously, this is not fun at all. I just did npm install -g n today and now I want to unsintall it and it will not. I run the command. Than I look in the system, n is still there. A big thumbs down!

**Comment by shadowspawn** [comment]
@bngbog you did not say what command you ran to uninstall or where in the system `n` remained, but to uninstall the `n` executable which you installed using `npm install -g n` you use:

```sh
npm uninstall -g n
```
