### ISSUE TITLE
n cannot find already installed node

### ISSUE THREAD

**Issue by maicWorkGithub** [tj/n#340]

**Comment by Jonnymcc** [comment]
Are you using a custom N_PREFIX? I've noticed that if a node version is installed somewhere in your path and you use n to install the same version it fails to install it in the N_PREFIX dir because the check for which version is installed uses the other node installed somewhere on your path.

ex. node latest installed at /usr/bin/
PATH=~/n:/usr/bin:...
N_PREFIX=~/n
`n latest` checks version and sees that latest is already installed at /usr/bin
so it does not install node in ~/n

**Comment by wlsf82** [comment]
Is there any ETA for solving this?
