### ISSUE TITLE
"Stable" to "Current"

### ISSUE THREAD

**Issue by tleb** [tj/n#354]
> We will be using the `Current` label from here-on instead of `Stable`.
> — https://nodejs.org/en/blog/release/v6.0.0/#current-what-happened-to-stable

**Comment by tedgaydos** [comment]
Thanks for the info. We will take it into consideration.

The dist folder was restructured. Looks like we can easily support commands like `n latest`, `n latest v0.10`, `n latest v4`, `n io latest v1`, and `n lts`.

We would also remove the `stable` keyword.

**Comment by shadowspawn** [comment]
Fixed `stable` in #467
More recent and extensive comments in #522

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
