### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by showzyl** [tj/n#368]
➜  t n latest
cp: /usr/local/n/versions/node//bin: No such file or directory
cp: /usr/local/n/versions/node//lib: No such file or directory
cp: /usr/local/n/versions/node//include: No such file or directory
cp: /usr/local/n/versions/node//share: No such file or directory

how can i fixed this question?

**Comment by qertis** [comment]
+1

**Comment by qw3rtman** [comment]
Have you run `n` on its own yet? If so, does it produce the same error?

**Comment by wvicente** [comment]
same here o/
nothing works, but on 2 different servers: in CentOS I get this error, but my Ubuntu works fine.

**Comment by visionscaper** [comment]
Same here. I'm on macOS Sierra.

    n -V
    2.1.3

    sudo n stable
    Password:
    cp: /usr/local/n/versions/node//bin: No such file or directory
    cp: /usr/local/n/versions/node//lib: No such file or directory
    cp: /usr/local/n/versions/node//include: No such file or directory
    cp: /usr/local/n/versions/node//share: No such file or directory

**Comment by qw3rtman** [comment]
@visionscaper, do you get an error when you run `n` on its own?

**Comment by visionscaper** [comment]
Hi @qw3rtman,

I've been doing many different thinks yesterday, but as far as I can remember this occurred because the use of a proxy was not properly set up: now I don't have this issue anymore. n on it's own worked and produced the list of installed node versions.

Does this make any sense to you (fix by fixing proxy)?

Kind regards,

Freddy

**Comment by hhsl** [comment]
Hi, I made it work using "sudo -E n stable" under Ubuntu. There definitely seems to be some problem with proxys.
