### ISSUE TITLE
Allow switching between local versions using major version number when internet is not available

### ISSUE THREAD

**Issue by Corluhan** [tj/n#377]
Say I have 2 versions installed:

```
    node/0.12.16
  ο node/6.7.0
```

I can easily switch between them when specifying the full version number:

```
$ sudo n 0.12.16
$ sudo n 6.7.0
```

This doesn't work with the major numbers:

```
$ sudo n 6.

  Error: invalid version 6.

```

The ideal behavior is to select the latest installed version with the specified major version number.

**Comment by qw3rtman** [comment]
@Corluhan: Is this only an issue when you have no Internet connection?

**Comment by shadowspawn** [comment]
This is an interesting idea, but would need a different approach to clarify the two different behaviours of picking latest local version or latest downloadable version.  

A simple workaround is to use the menu selection and pick from the installed versions.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
Added --offline option in n v9.2.0
