### ISSUE TITLE
why I can't install n on my operating system?

### ISSUE THREAD

**Issue by a526672351** [tj/n#419]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "n"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: n@2.1.5
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

**Comment by tracker1** [comment]
Because of how windows applications are generally installed... it might be possible to create an "n" installer that installs only for your user, then adds that path to your user's environment `PATH` ...

There's an [nvm for windows](https://github.com/coreybutler/nvm-windows/releases), though the interface is slightly different from regular nvm (it's written in go), but it requires elevated privileges each time you run it... this is because it sets the %ProgramFiles%/node as a symlink to the downloaded version you install.

Any similar script via n would probably have similar shortcomings, but I haven't really looked... it will take some elevation to set the user's path environment at the very least... and symbolic linking wouldn't be a clean option... so would need to update the path each time... unsure of what's there for the windows env in node to support that (may well require the windows dev environment setup and working).

**Comment by troy0820** [comment]
The README says:
> Unfortunately n is not supported on Windows yet. If you're able to make it work, send in a pull request!

I would try nvm for Windows.
