### ISSUE TITLE
unable to install node-v0.6.5

### ISSUE THREAD

**Issue by RichLewis007** [tj/n#420]
# Issue Template:

### Describe issue including what OS you are using

_i.e. I'm using MacOS Sierra_

### Describe what version of N you have
_i.e. n --version output: 2.1.4_
2.1.5 latest

### Describe how you installed N

* _i.e. npm install -g n_
* _i.e. make install_
some crazy shell script you suggest in your readme

### Steps to reproduce issue _1.2.3_
_i.e._
1. n latest
2. couldn't pull latest from source

n 0.6.5
### Describe the results you received

see: install : node-v0.6.5

  Error: invalid version 0.6.5

### Describe the results you expected

_i.e. I was supposed to see the lastet being pulled from source_

I was supposed to get node 0.6.5 installed..

### What version of npm you are using

_i.e. npm --version output: 4.0.5_

4.1.2
### Additional information you deem important (e.g. issue happens only occasionally):

* Output of `which n:`
* Output of `node -v:`
node -v: 7.6.0

I was able to install node stable and latest fine.

**Comment by troy0820** [comment]
Here is your problem on this line in `bin/n`
>   echo "${MIRROR[$DEFAULT]}v${version}/${BIN_NAME[$DEFAULT]}-v${version}-${os}-${arch}.tar.gz"

`N` is looking for a dist folder with the ` https://nodejs.org/dist/v0.6.5/node-v5.6.0-linux-x64.tar.gz` not `https://nodejs.org/dist/v0.6.5/node-v0.6.0.tar.gz ` which is the only one available.

It is still a valid node version but not what N is expecting.  That version of node is no longer supported and I'd advise not using it honestly.  To fix this would mean to try to support versions of node that are way beyond support.  

I would try n lts if you want to use node in its current state.

**Comment by RichLewis007** [comment]
Thanks. I was trying to run some old code that was written for that version of node.js 

When I use the "n ls" command, all of the old node versions are listed. Should n only list the versions that it can install? Which ones can it install, going back?

**Comment by troy0820** [comment]
`n ls` lists every version that is available at https://nodejs.org/dist/.  These versions are still valid but the `n` script doesn't try to install those versions that are not specific to the Linux platform.  That is why it doesn't work for windows.  I believe that they used this convention when making this script because of the fact that older versions were unstable.  

I'm not sure what version you need, but version 0.10.0 seems to work and they usually backport the fixes.  I would try  `n 0.10.0` to see if you can run that code.

**Comment by RichLewis007** [comment]
Thanks!
