### ISSUE TITLE
Not working with alpine:3.2+

### ISSUE THREAD

**Issue by dev-mraj** [tj/n#431]
Hi,
its not working with alpine 3.2 in docker..

i don't even list version using "n ls"
### Describe issue including what OS you are using
Alpine 3.2

### Describe what version of N you have
2.1.7

### Describe how you installed N
npm install -g n

### Steps to reproduce issue _1.2.3_

docker run -it alpine:3.4 sh
 apk add bash nodejs --update
npm i -g n
n ls

### Describe the results you received
blank screen

### Describe the results you expected
list the versions

### What version of npm you are using
3.10.3

### Additional information you deem important (e.g. issue happens only occasionally):

* Output of `which n:` /usr/bin/n
* Output of `node -v:` v6.7.0

**Comment by troy0820** [comment]
Originally when this was designed these OS's were not the target.  One reason you can't see any of the versions is that` alpine` in itself doesn't really come with anything.  So you need `curl` to actually hit the endpoint where the versions are listed.  That will get you as far as `n ls`.  To download any versions because the packages are stripped down you will need a lot of other packages, including `tar`,`unzip`, etc.  I made a docker image that you can use that uses the ubuntu 16.04 with n called `troy0820/node-n`.  I also have another docker image called `troy0820/node-n-fedora`

In the meantime, I will be looking at a way to make an image from alpine 3.2 that can solve this problem.

**Comment by troy0820** [comment]
I also have a docker image you can try called `troy0820/node-centos-n:6.6` to try your hand at that image if you need it.  @dev-mraj

**Comment by troy0820** [comment]
Did you try to add any other packages that I listed above?  Docker images, especially alpine, have the necessary things you need to run n.  You must install them yourself.  You need curl, tar, zip, etc.  Try the docker image listed above.  I'm working on an alpine container that will be built from using mulistage builds that may help you.

**Comment by dancrumb** [comment]
@troy0820 adding `curl` helped - is there any way for n to sensible report that it's problems are due to an absence of `curl`, rather than just returning nothing?

**Comment by dancrumb** [comment]
Looking at the source, it appears as if it's also supposed to support `wget` and only errors out if both are missing... is it possible that `wget` is actually _not_ supported?

**Comment by JohnRGee** [comment]
`n` is not likely to be useful on Alpine, because it downloads the prebuilt Linux  Binaries from [nodejs downloads](https://nodejs.org/en/download/) which do not run on Alpine. While you can get `n` working by adding a few packages, the downloaded binaries require `glibc` et al (#344). Alpine comes with a different `libc` called [musl](https://www.musl-libc.org/faq.html).

If you are working with containers then the [official docker images](https://hub.docker.com/_/node/) do include [node:alpine](https://github.com/nodejs/docker-node#nodealpine) so this is a good base image for using node on Alpine.

(From investigations, the extra trick getting `n` running on Alpine 3.2 is that it has a version of `wget` that does not support `--spider`. A work-around is to add `curl`. e.g. `apk add bash tar openssl ca-certificates curl`)

**Comment by shadowspawn** [comment]
Instructions for installing node on Alpine using unofficial node mirror: https://github.com/tj/n/issues/648
