### ISSUE TITLE
prune: Uninstall all versions except latest & lts

### ISSUE THREAD

**Issue by avrelaun** [tj/n#452]
I use n to update easily my node version, and use only the latest stable and lts, although I switch between the two.

Keeping the old versions are not relevant in my use case, and it would be nice to be able to keep only the latest supported versions of each branch.

One possible way to achieve this today is:

`n prune && n lts && n latest`

But it downloads lts everytime and it forces n to latest even if I was on lts.

**Comment by troy0820** [comment]
Please use the issue template when filing issues:

The above command is going to prune whatever version is not active, and then download lts and activate it, then it will download latest and active latest.  So yes, it will force you to latest.  So if you had these versions installed `v4.6.0` `v6.0.0` and `8.0.0` and was on `4.6.0` doing what you did above would erase everything except 4.6.0 and then re download lts and latest.  If what you are trying to achieve is different than that, you can follow these instructions. 
 
N has a `n rm` function that can remove versions that you don't need.  With that said, you can remove the unnecessary versions to your liking without having to use prune.  You can remove the version that you are not using and still install the one you need.  

If you want to keep the latest lts and latest, you can n prune while on latest and reinstall lts like 
`n latest && n prune && n lts` which will leave you on the lts branch.

I'm closing this issue because it's not a feature request, or a bug.
