### ISSUE TITLE
[REQUEST] The last version its not compile for ARMv6 ... 

### ISSUE THREAD

**Issue by andrelec1** [tj/n#463]
# Issue Template:

### Describe issue including what OS you are using

_ RASPBIAN STRETCH LITE - September 2017

### Describe what version of N you have
_ 2.1.7

### Describe how you installed N

_  npm install -g n

### Steps to reproduce issue _1.2.3_

1. n latest

### Describe the results you received

_ get Error: invalid version -v

### Describe the results you expected

I use a old raspberry on ARMv6 ...
and i loose too many time juste beaucause nodejs.org doesn't compile the last version for ARMv6 (10/5/17 , 2PM )
But version existe, juste not available for architecture...

Its possible for 'n latest' and 'n stable' to auto downgrade version if the last its not available for the current architecture ?

**Comment by drkale44** [comment]
Hi

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report. The work for #560 will make this much easier (using `index.tab` instead of screen scraping to get version info.)

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
Prerelease available via `npm i n@next` for v6. Release notes: https://github.com/tj/n/releases/tag/6.0.0-0
