### ISSUE TITLE
ChakraCore via n?

### ISSUE THREAD

**Issue by D219** [tj/n#480]
Since n already support installing io.js, are there plans to also make [ChakraCore](https://github.com/nodejs/node-chakracore/releases) available via n?

**Comment by JohnRGee** [comment]
I am having a go at this in a fork and using syntax like chakracore-release/<version>, influenced by nvs. If it works out sanely I'll look at a PR.

**Comment by shadowspawn** [comment]
I have added support for ChakraCore in [nvh](https://github.com/shadowspawn/nvh). It will be a while before it gets considered for `n`, and if you give it a try in `nvh` then I am interested in feedback about how useful it is in practice.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. I am interested in eventually adding LTS codenames, chakracore, nightly et al, but not likely to happen due to this issue alone.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
