### ISSUE TITLE
[Request] cli command to set node version for specific project directory

### ISSUE THREAD

**Issue by awidjaja** [tj/n#481]
nice tool. 

Is it possible to add a cli command to set node version for specific project directory, by specifying the version as parameter or by checking node version in the package.json file?

I think it can be implemented as link from the project's node_modules/.bin to the correct node binary.

**Comment by kassi** [comment]
@awidjaja I'm testing `n` now and created a small bash function:

    function load-node-version {
      if [[ -f .node-version ]]; then
        n $(cat .node-version)
      fi
    }
    function cd {
      builtin cd "$@"
      load-node-version
    }

When I create a file `.node-version` with content e.g. `8.9.4`, it will switch to the specified node version whenever I cd into this directory.
However, since `n` just replaces the `/usr/local/bin/node` with a different version (at least that's what I understood), it will change it for the whole system, not only for the shell in the current directory. So playing around with 2 projects with different node version requirements in parallel won't work.
I also encountered that switching node versions takes some time, i.e. 10 to 20 seconds or more.

**Comment by awidjaja** [comment]
@kassi , thanks, however, one can simply type 'n <version>' on the command line for the same result. 

What I was looking for is an automatic redirection of 'node' command to the node binary in the right folder (for the version), skipping the default /usr/local/bin/node on the path, when node version is specified in the package.json file.

**Comment by JohnRGee** [comment]
This request overlaps with #477. The example there is `rbenv`, which shims all the ruby related commands to allow a local override when in that directory.

[avn](https://github.com/wbyoung/avn) supports n, and like the approach suggested by @kassi is changing the installed version of node when you change directory.

If you only want to launch node directly, a script which checks for the local version and calls `n use <version> [args]` would be fairly simple (and limited).

**Comment by JohnRGee** [comment]
Of possible interest (and uses nodemodules/.bin as suggested by @awidjaja): https://www.npmjs.com/package/node

**Comment by awidjaja** [comment]
@JohnRGee , thanks for the link, this will meet my need. 

Although in my opinion, this is the domain of n which already provides ability to install several node versions at the same time, and basically just need a command to add a link to the right node binary in the node_module/.bin inside the project directory. 

I will close the issue.
