### ISSUE TITLE
Doesn't work on High Sierra

### ISSUE THREAD

**Issue by ahmedmusawir** [tj/n#533]
# Issue Template:

### Describe issue including what OS you are using

_i.e. I'm using MacOS Sierra_

### Describe what version of N you have
_i.e. n --version output: 2.1.4_

### Describe how you installed N

* _i.e. npm install -g n_
* _i.e. make install_

### Steps to reproduce issue _1.2.3_
_i.e._
1. n latest
2. couldn't pull latest from source

### Describe the results you received

_i.e. blank screen_
### Describe the results you expected

_i.e. I was supposed to see the latest being pulled from source_

### What version of npm you are using

Mooses-High-Sierra:~ moose$ npm -v
6.4.1

### Additional information you deem important (e.g. issue happens only occasionally):

Mooses-High-Sierra:~ moose$ node -v
v10.10.0
Mooses-High-Sierra:~ moose$ n rm 10.10.0
Mooses-High-Sierra:~ moose$ node -v
v10.10.0
Mooses-High-Sierra:~ moose$ sudo n rm 10.10.0
Mooses-High-Sierra:~ moose$ sudo n - 10.10.0
Mooses-High-Sierra:~ moose$ node -v
v10.10.0

**Comment by JohnRGee** [comment]
`n` keeps a cache of downloaded node versions so that when you reinstall a version it does not need to download it again. You see the available cached versions when you run `n` without any parameters.

The `rm` command removes the downloaded version from the cache (if present), but does not uninstall node . So running `n rm` does not affect `node -v`.

`n` leans towards minimal messages. In this case you said you don't want 10.10.0 in the cache, and it wasn't, so `n` assumes you are happy with the result!

**Comment by ahmedmusawir** [comment]
Thanx for your reply. I just got nvm and it's all good.

**Comment by JohnRGee** [comment]
Ok. Suggest you close this issue then.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
