### ISSUE TITLE
Use .nvmrc with n

### ISSUE THREAD

**Issue by spences10** [tj/n#547]
Hi,

Is there a way to use an `.nvmrc` file with `n`?

@gussyboy touched on it in another issue #423 but @JohnRGee seemed to be confused by the comment.

So, so there is no confusion around what I am requesting, I would like to know if it is possible to configure a project that uses node, to use a specific version of node. This sort of behaviour is possible *(as I understand it) with a `.nvmrc` file.

Is there a way to do this if I'm an `n` user and the rest of my team are `nvm` users.

Thanks

**Comment by JohnRGee** [comment]
I can see a limited but simple way to use `.nvmrc` with `n`, assuming version number specified in compatible way::

```sh
alias ni='n $(cat .nvmrc)'
alias nr='n run $(cat .nvmrc)'
```

**Comment by JohnRGee** [comment]
Configuring a project that use node, to use a specific version of node, is complex. One option more in that spirit is: https://www.npmjs.com/package/node

**Comment by spences10** [comment]
Thanks, I'll try, closing this for now.

**Comment by shadowspawn** [comment]
On a related note, I have added support for reading a `.node-version` file in `n` 6.5.0.

**Comment by adrianmcli** [comment]
@shadowspawn I appreciate the new feature, but there are many existing projects with `.nvmrc` files. I know that a non-tool specific dotfile would be more ideal. But to make it easy for people to transition from NVM to `n`, do you think maybe we can add the ability for `n` to be configured to read from `.nvmrc` as well?

**Comment by shadowspawn** [comment]
1) `.nvmrc` is a propriatory configuration fie for a specific node version manager. I don't think many people are going to transition from `nvm` to `n`, but a situation I am interested in is teams which may be using both and possibly other tools too. What I would rather support for cross-tool compatibility is `.node-version`, but I got some pushback on adopting that before it was a _standard_ (not from a user).

https://github.com/nodejs/version-management/issues/13

2) `engines.node` is a challenge because `n` is implemented as a shell script, and parsing `json` is non-trivial. However, I am open to the idea. I suggest you open new issues for the ideas you care about to see if there is support for them from other users.

**Comment by adrianmcli** [comment]
@shadowspawn Thanks for the reply.

1. I understand the push for `.node-version`, but the fact is that `.nvmrc` is vastly more popular and as an avid `n` user, I (and many others) have run into problems when getting onboarded to projects with `.nvmrc`. Of course it's not something I couldn't deal with manually, but it's a huge hassle especially if you are switching in and out of projects on a daily basis.

   I understand the proprietary nature of `.nvmrc` might make it sound odd to support, but I don't see a downside to supporting something proprietary. For example, Google Docs support exporting of Microsoft Word files even as a direct competitor. And numerous non-Adobe graphic design software support reading and writing Adobe Photoshop and Illustrator files.

2. Understood, I will create a new issue for this specifically.

**Comment by shadowspawn** [comment]
1)To be clear, I am not completely against limited support for `.nvmrc` if there is demand for it. Since `auto` is an explicit opt-in target, I am ok with looking in multiple locations for the desired version and even "having a go".

**Comment by MarkLyck** [comment]
Please add support for `.nvmrc` 🙏

**Comment by shadowspawn** [comment]
New issues have been opened for:
- node.engines #618 
- .nvmrc #625
