### ISSUE TITLE
Unbrewed header files

### ISSUE THREAD

**Issue by tborychowski** [tj/n#567]
# Issue Template:

Is there a way to make it compatible, so that the homebrew doesn't complain about this?

### Describe issue including what OS you are using
MacOS Mojave

### Describe what version of N you have
4.1.0

### Describe how you installed N
```sh
npm install -g n
```

### Steps to reproduce issue _1.2.3_
1. `n latest`
2. run `brew doctor`

### Describe the results you received

```
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/js_native_api.h
  /usr/local/include/node/js_native_api_types.h
  /usr/local/include/node/libplatform/libplatform-export.h
  /usr/local/include/node/libplatform/libplatform.h
  /usr/local/include/node/libplatform/v8-tracing.h
  /usr/local/include/node/node.h
  ...
```

### Describe the results you expected
Clean output.

### What version of npm you are using
6.9.0

**Comment by shadowspawn** [comment]
You get the same warnings if you installed node using the package installer from nodejs.org.

To eliminate the `brew doctor` warnings, I think your two main options are: 
- define `N_PREFIX` and use `n` to install to a location that `homebrew` does not care about (such as a folder in your home directory)
- install `node` using homebrew (instead of `n`)
