### ISSUE TITLE
why isnt windows supported

### ISSUE THREAD

**Issue by Milo123459** [tj/n#626]
why isnt windows supported?

**Comment by shadowspawn** [comment]
Why not native Windows?

- `n` is implemented as a bash script, and `bash` is not natively supported on Windows
- `n` downloads prebuilt tarballs and just unpacks them into place using Unix/Linux tools

Why not WSL?

- it can work, see #511
- it isn't supported because the people who contributed PR around improving support in WSL were no longer using `n` on Windows when I asked questions, and I don't have a Windows computer myself to nail down the details.

**Comment by shadowspawn** [comment]
Related: #146 #161 #254 #311 #442 #552

**Comment by Milo123459** [comment]
Thanks!
