### ISSUE TITLE
Install to custom path

### ISSUE THREAD

**Issue by vladimircores** [tj/n#631]
Please add an option to install `n` at custom path from installer, currently it installed in the home directory which breaks my "feng shui"
![Screen Capture_select-area_20201012201950](https://user-images.githubusercontent.com/442111/95778896-55a88780-0cc9-11eb-9af4-6a28973d2f89.png)

**Comment by shadowspawn** [comment]
When you say "installer", how did you install `n`?

The folder where downloaded node versions are cached is set using `N_PREFIX` to change the default location, which is `/usr/local/n`.

**Comment by vladimircores** [comment]
@shadowspawn I think it was curl version I used to install `n`

**Comment by shadowspawn** [comment]
By default, `n` does not install to your home directory, and does not use your home directory as the place to store downloads. So that `n` folder is from something that got done when you were installing or setting up `n`.

To find out how you currently have things set up, try running these to find out where the n binary is and what the environment variable is:

```sh
command -v n
echo $N_PREFIX
```

**Comment by vladimircores** [comment]
Here it:
```
vladimir:~$ command -v n
/home/vladimir/n/bin/n
vladimir:~$ echo $N_PREFIX
/home/vladimir/n
```
But my request is about adding an prompt to installer which asks for perfectible installation path.

**Comment by shadowspawn** [comment]
Ok, but which installer? There are lots of ways of installing `n`. Did you perhaps use `n_install`?

https://github.com/tj/n#installation

**Comment by vladimircores** [comment]
It was curl way `curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n`

**Comment by shadowspawn** [comment]
I may still not be understanding what you are asking.

What that `curl` line does is download the `n` shell script to the current directory so that you can run `n` directly without needing node and npm first. It doesn't install anything, or make an `n` directory in your home folder.

You currently have an `n` folder in your home folder, and your environment variables have an entry in your `PATH` variable so that it finds a copy of the `n` shell script in `/home/vladimir/n/bin/n`, and `N_PREFIX` is set to your home folder. None of those happen just by running the `curl` command or just by running `n` itself.

I don't know what steps you followed to get to that state, so I don't know where there could be a prompt to ask for the installation path.

**Comment by shadowspawn** [comment]
You can tell if the shell startup entries were created by `n-install` as it adds a comment:

```
# Added by n-install (see http://git.io/n-install-repo).
```

(I keep mentioning `n-install` as it is the only automated way of installing `n` to your home folder that I am aware of.)

**Comment by vladimircores** [comment]
Oh, I'm sorry copied wrong curl command I used this one - `curl -L https://git.io/n-install | bash`

**Comment by shadowspawn** [comment]
Ah ha! 😄 

`n-install` is a separate project: https://github.com/mklement0/n-install

There are instructions on its home page for installing into a different directory and various custom setups. 

You could open an issue there suggesting a prompt in the installer.

**Comment by shadowspawn** [comment]
Closing as answered in `n-install`: https://github.com/mklement0/n-install/issues/32#issuecomment-713378259
