### ISSUE TITLE
install version fails, don't know why.  is there a debug mode 

### ISSUE THREAD

**Issue by sdetweil** [tj/n#699]
# Problem
installing node 14 on Raspberry pi bullseye (latest release oct, 30, 2021

my installer code does 
```
                   # I install n
                nr=$(sudo npm install -g n)
                   # which seemed to work
                   # then used n to install node 14
		sudo n i ${NODE_TESTED:1:2} >> $logfile
                     PATH="$PATH"
		     nodev=$(node -v)
		     if [ "${nodev:0:3}" != ${NODE_TESTED:0:3} ]; then
			echo node failed to install, exiting | tee -a $logfile
			exit
	             fi
```

which produces this on users system 
```
installing : node-v14.18.1
mkdir : /usr/local/n/versions/node/14.18.1
fetch : https://nodejs.org/dist/v14.18.1/node-v14.18.1-linux-armv7l.tar.xz
node failed to install, exiting
```
on my test system in US, on wired ethernet
```
  installing : node-v14.18.1
       mkdir : /usr/local/n/versions/node/14.18.1
       fetch : https://nodejs.org/dist/v14.18.1/node-v14.18.1-linux-armv7l.tar.xz
   installed : v14.18.1 (with npm 6.14.15)

Note: the node command changed location and the old location may be remembered in your current shell.
         old : /usr/bin/node
         new : /usr/local/bin/node
To reset the command location hash either start a new shell, or execute PATH="$PATH"
```

## Configuration Details

```bash
$ n --version
pi@raspberrypi4:~ $ n --version
v8.0.0


$ command -v node
pi@raspberrypi4:~ $ command -v node
/usr/local/bin/node


$ node -p process.platform
pi@raspberrypi4:~ $ node -p process.platform
linux

other info 
pi@raspberrypi4:~ $ uname -a
Linux raspberrypi4 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux

pi@raspberrypi4:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

```

**Comment by shadowspawn** [comment]
Some questions and musing and suggestions.

There is not a debug mode.

I am a bit confused about what you are displaying from users system and from your system, with the redirection to the log 
file and stdout vs stderr. Is the output from your system just running `n` rather than your installer? Can your user do the same?

The warning message you see about `PATH` changing may mean you get a false-positive failure due to seeing the version number of the system installed node if it was not node v14. However, your user is not seeing the "installed" log line or the PATH warning so my theory does not match the observations.

1) You can run `n doctor` to output some configuration information and test for some known configuration problems.

2) If the fetch failed, I would hope to see some sort of error message. Unless you are deliberately capturing just stdout, your could capture both stdout and stderr by changing:

```
sudo n i ${NODE_TESTED:1:2} >> $logfile
```

to

```
sudo n i ${NODE_TESTED:1:2} &>> $logfile
```

But if stderr is visible in the environment the installer is being run, it would still be visible.

**Comment by sdetweil** [comment]
sorry left out info

I support the scripted installer for MagicMirror.
https://github.com/MichMich/MagicMirror

on  latest release, bullseye, node is 12.27.we need node 14.

the installer script use n to handle the upgrade

**Comment by shadowspawn** [comment]
Hoping there are some clues as to what is failing on stderr. 🤞 

https://github.com/sdetweil/MagicMirror_scripts/issues/36

**Comment by shadowspawn** [comment]
The underlying problem is no longer reproducible, no further information available about the failure, and no further activity in a month. Nothing to do here for now. 😅 

Feel free to open a new issue if it comes up again, with new information and renewed interest.
