### ISSUE TITLE
zsh: command not found: n

### ISSUE THREAD

**Issue by afloury** [tj/n#709]
# Problem

I try to install n then use it but it's not working for me.

## Short Version

I followed the installation with npm then when I try to use the command it says : `zsh: command not found: n`

## Long Version

I was on old Node version 10.x
I install last LTS Node version on https://nodejs.org/en/ (16.13.2) to start a new project in VueJS, but my old project for my job stop working with this version so I wanted to install n to manage my Node versions

I do : 
`% npm install -g n`
`added 1 package, and audited 2 packages in 653ms`
`found 0 vulnerabilities`

then :
`sudo mkdir -p /usr/local/n`
`sudo chown -R $(whoami) /usr/local/n`
`sudo mkdir -p /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share`
`sudo chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share`

```bash
% ls /usr/local 
bin	include	lib	n	share
```

then :
`% n`
`zsh: command not found: n`
`% which n`
`n not found`

## Configuration Details

```bash
% n --version
zsh: command not found: n

% command -v node
/usr/local/bin/node

% node -p process.platform
darwin

% echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin

# I'm on macOS Monterey
# MacBook Pro (16 pouces, 2019)
# I have an intel processor, it's not a M1

```

_Ask me if you need more infos_

**Comment by shadowspawn** [comment]
Thanks for the good detail. I didn't spot a problem so far.

What does this show?

```
npm prefix --global
```

**Comment by mrtorks** [comment]
@shadowspawn I was also going to echo in addition that .zshrc needs to be inspected for $PATH configuration.

**Comment by afloury** [comment]
@shadowspawn Thanks for answering, this is what I got :
```Bash
% npm prefix --global 
/Users/nanimans/.npm-global
```

**Comment by shadowspawn** [comment]
Ah ha. You have a custom location, and the `bin` folder from there is not in your `PATH` so globally installed npm packages with binaries (like `n`) are not being found on command line.

If you are comfortable with  npm global packages being runnable, you could add to your `PATH`. If you don't want npm global packages runnable automatically you could install `n` a different way. Do you know why you have a custom location? (No slight intended! I know it is easy to accumulate configuration over the years...)

Ask more questions or indicate a preference for direction, and I'll fill out some more details later.

**Comment by afloury** [comment]
I don't totally remember but I think it's when I switch from windows to my new Mac, I try to make my project works and maybe I follow some commands in GitHub or StackOverflow comments to get it works and when it works I just let it like that.

Now I realize that I need to more understand what I do, but when it's for my job it's difficult to do task in time and understand all aspect of tools we use.

So it's not totally clear for me, you tell that my bin folder is not in my `PATH` but in my `echo $PATH` I got some path to different bin folders, so what I don't understand ?

About you question I don't know what is the best option but until here it was not a problem for me with this config (npm global packages being runnable) but if it's not a good practice I can change it.

So when you said install `n` in a different way, you mean without `npm` so install with Homebrew for example ?

Thanks a lot for taking the time to help me 🙏 
_Sorry if I feel a little lost in all of this and english is not my main language_

**Comment by shadowspawn** [comment]
My message was pretty vague, written quickly, sorry! 

Thanks for the extra info. I will write up some more detailed advice now I have a better understanding.

**Comment by afloury** [comment]
_I don't know if it's important or explain maybe the choice I made before, but I use WebStorm and I use Run configuration to launch my project directly from Webstorm_

**Comment by shadowspawn** [comment]
First story. This is for your information, and you don't need to change anything! (No mention of PATH in this story, see the next story for that.)

If on a fresh computer you install Node.js (node and npm) and then try and install a global package, you get a permission error. e.g.

```
$ npm install -g n
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/n
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/n
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/n'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/n'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/n'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

This is expected behaviour. The default location for `npm` is `/usr/local/bin/npm`. The default location npm uses for global packages is "beside" npm in `/usr/local/lib/node_modules`. The default permissions are users can not write to this location.

So, what to do? Four different approaches.

1) Just stick `sudo` in front of command? No! No! No! This is often suggested because it is so easy but is a bad idea in general. npm installs can run arbitrary scripts, so running them with `sudo` is a bad idea from a security point of view.

2) If it is a personal computer, you might change permission of folders so you can write to the folders need for `npm` global packages. This is what Homebrew suggests as part of its setup. (NB: some people do not like changing permissions on system folders which is a valid view. I decided changing permissions was a reasonable compromise on "my" computer for convenience, to use default install locations.)

Note: this command you ran was to change the permissions on the folders used by node and npm to allow you to install without using sudo:
```
sudo chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
```

3) Use a node version manager, and install and run node and npm out of your home folder. Then when npm installs the global packages "beside" itself, it is in your home folder. Changing the Node.js install location is what `N_PREFIX` is for, and what `n-install` does for you.

4) Change the prefix so npm install global packages somewhere else. This is what you may have done. e.g.

```
$ npm config set prefix '/Users/nanimans/.npm-global'
```

**Comment by shadowspawn** [comment]
Second story. What about `PATH`?

The `PATH` environment variable tells the shell where to look for executable files. When you type `node` or `n` the shell looks in the list of locations. `PATH` is a list of folders separated by `:`.

To let you run executables from npm global packages, you need to have their install location in your `PATH`. The executable part of the packages is in the `bin` folder under where npm put the packages.

So with your current setup, you can put a line like this in your shell startup file (e.g. `.zshrc` if you are running `zsh`):

```
export PATH=/Users/nanimans/.npm-global/bin:$PATH
```

That adds the npm globals folder in the front of the search, and exports it so sub shells see it too.

-----

If you reset your npm configuration and install everything to the default locations, you do not need to alter `PATH` because `/usr/local/bin` is already included in the search locations by default on Mac.

-----

If you tell `n` to install Node.js to your home folder, and npm installs global packages to its default location, then you need to add that location to the search path. That is what these lines do in the README. Notice that `bin` folder again.

```
export N_PREFIX=$HOME/.n
export PATH=$N_PREFIX/bin:$PATH
```

**Comment by shadowspawn** [comment]
I suggest using a node version manager AND a custom location for npm global packages is a bit too complex unless you know what you are doing. So you might want to remove the setting for custom npm prefix.

But maybe something in your setup now relies on this, so the easiest thing with your current setup is just:

```
export PATH=/Users/nanimans/.npm-global/bin:$PATH
```

After adding that, `n` should be a recognised command when you open a new shell.

See if you can make sense of enough of all that information, and hopefully it will give you more clues for reading other descriptions on the internet too.

**Comment by shadowspawn** [comment]
See if you can make sense of enough of all that information, and hopefully it will give you more clues for reading other descriptions on the internet too! 🤯 😄

**Comment by afloury** [comment]
Thanks you so much for all this explanations, I learn a lot from this infos (after reading it more than 10 times 😄) and it give me a lot of clues to search and understand all of this, this was very interesting, and I will explain what I did so maybe it can help someone reading this in the future.

So I understand that the solution to add the location to my custom npm global `/Users/nanimans/.npm-global/bin` to the `PATH` can resolve the problem because it will fix the access of global packages that normally should be in `/usr/local/lib/node_modules` but after learning so much I have more understanding of what I do and I didn’t want to chose the easy way, so I try to fix my current config to return back to default.

To reset the config I was not sure what to do, I thought do something like `npm config set prefix '/usr/local/lib/node_modules'` but these seems confuse to me because this location is not mention in the `PATH` so it’s seems weird as a default config for prefix, I search about how to reset default config for npm and I found this ([https://stackoverflow.com/questions/20934343/how-to-restore-reset-npm-configuration-to-default-values](https://stackoverflow.com/questions/20934343/how-to-restore-reset-npm-configuration-to-default-values))

So I try just `npm config get userconfig` and I get `/Users/nanimans/.npmrc` the run config file of npm (some people will think “yeah it’s obvious” ahah) and in this file there is the config of the prefix `prefix=~/.npm-global` the answer seems valid for other user so I try `echo "" > $(npm config get userconfig)` I was expecting this will empty the .npmrc but I try `npm prefix --global` and I get `/usr/local` this makes more sens as `/usr/local/bin` is in the `PATH` by default, to be sure I did :

```Bash
nanimans@MacBook-Pro-de-Antoine ~ % ls -a /usr/local/lib/node_modules
.		@vue		npm
..		corepack

nanimans@MacBook-Pro-de-Antoine ~ % n
zsh: command not found: n

nanimans@MacBook-Pro-de-Antoine ~ % npm install -g n
added 1 package, and audited 2 packages in 2s
found 0 vulnerabilities

nanimans@MacBook-Pro-de-Antoine ~ % ls -a /usr/local/lib/node_modules
.		@vue		n
..		corepack	npm
```

Then this works :
```Bash
nanimans@MacBook-Pro-de-Antoine ~ % n 10.19
installing : node-v10.19.0
mkdir : /usr/local/n/versions/node/10.19.0
fetch : [https://nodejs.org/dist/v10.19.0/node-v10.19.0-darwin-x64.tar.xz](https://nodejs.org/dist/v10.19.0/node-v10.19.0-darwin-x64.tar.xz)
installed : v10.19.0 (with npm 6.13.4)
nanimans@MacBook-Pro-de-Antoine ~ %
nanimans@MacBook-Pro-de-Antoine ~ % n
installed : v10.19.0 (with npm 6.13.4)
nanimans@MacBook-Pro-de-Antoine ~ % npm -v
6.13.4
```

I also move my custom `.npm-global` into a temp folder to be sure it still working without it, I hope I haven't forgotten anything, I test the app of my job it seems to work well with old version installing with `n` (10.19), I will try to install a recent version of Node with `n` later and set up a new vuejs project but I'm confident about it now.

Thanks again, because I thought that I was so lost and I feel that I don’t be able to understand all of this and step after step I did it by searching and understanding all parts of your explanations ! 😃

**Comment by shadowspawn** [comment]
There have not been many issues around custom npm prefix. You did a good job supplying enough information to help me work out that was the underlying issue.

Glad things are working for you now. Good luck!

(Keeping the old globals in a temp folder is a good paranoid step, to keep round for a while.)

**Comment by BTBMan** [comment]
did you source .zshrc file? @afloury

**Comment by afloury** [comment]
I don't touch the .zshrc file neither before nor after solving the issue, I left it as a default during the whole process. @BTBMan
