### ISSUE TITLE
when installing the version node stops working

### ISSUE THREAD

**Issue by sk8sta13** [tj/n#718]
![image](https://user-images.githubusercontent.com/6431332/160473511-5b67dc63-5fae-4fe8-be9f-cca191751175.png)

**Comment by shadowspawn** [comment]
It looks like perhaps something in the original install failed and perhaps created a bogus file.

1) Are you running the install from a shell and user with different PATH than the one you dropped back to?

2) What does this show?

```
ls -l /usr/local/bin/node
```

(The message after the install was because you have a separate version of node already installed in `/usr/bin/node` and if you want the freshly installed one active you will need to delete the other one of alter your PATH. See also `n doctor` for some diagnostic checks and installation details.)

**Comment by hiiro74** [comment]
I think he is trying to run n in Alpine which was already answered.
https://github.com/tj/n/issues/648#issuecomment-763176280

**Comment by shadowspawn** [comment]
This issue has not added any further detail in a month. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thanks @hiiro74 for possible cause.
