### ISSUE TITLE
Using original node version if no file found for auto version

### ISSUE THREAD

**Issue by artfulsage** [tj/n#726]
Hey! I like the idea of `auto` version, it's really cool and gives us some great posibilities. But I think that it would be nice to let use it not only inside nodejs-project directories but everywhere. So I suggest to use original (current installed) nodejs version if no file was found for auto version. For me it fits in `auto` concept. What do you think? I would like to provide a PR if you agree.

**Comment by shadowspawn** [comment]
I don't understand the scenario you are describing. What command are you running with `auto` where silently continuing to use current version would be desirable?

`n` currently displays an error for `auto` and `engine` if no control file found so the user knows that no version was implied, and might need to think about what folder they are in or what version of node they want to use.

**Comment by artfulsage** [comment]
I understand the current behaviour the same way as you described it. But this new behavior would make possible to create an alias `node = n run auto` and so we could use the node version dependent on current folder transparantly. Actually we will get a multiple installed versions behavior. Yes, there are limitations with npm version installed, but for experienced users and `yarn`-users I guess it wouldn't be a problem.

Also I see possible future improvement when there wouldn't be any need to copy current node binaries to `/usr/local/bin/node`. `n` should just store version of current pseudo-installed version in some file and use it inside `auto`-resolver. Still there is a problem with npm version but perhaps it could be solved some way with some aliases.

**Comment by shadowspawn** [comment]
Lots of comments!

I don't want to change the current behaviour which expects a configured auto version, based on current feedback. There have not been (other) requests, and in fact one issue raised because `n` was not showing an error: https://github.com/tj/n/issues/692#issuecomment-931848225

There could be an option to opt-in to this behaviour, or a different label. At the moment I don't think I would want to add it without this issue getting upvoted.

The fallback could run the installed version, or could run the matching version from the cache. The results are slightly different. I think the installed version might match the semantics of your intended usage better, but the cached version matches the semantics of the `run` command better.

This could be externally scripted by using `n ls-remote auto` to look for a configured version. That would let you try out the usage without needing to modify `n`.

> Also I see possible future improvement when there wouldn't be any need to copy current node binaries

`n run` and `n exec` do not copy the binaries.

> Still there is a problem with npm version

`npm exec` gives access to the `npm` version included in the target Node.js version. So in line with your alias for node, could have `auto-npm = n exec auto npm`.

**Comment by artfulsage** [comment]
I see. Perhaps there truly should be some new label, but all possible variants in my mind are close to `auto`. And I also think that it should use the installed version at least for now because we don’t know which cached version is installed to `run` it. But if we knew then I don’t see many reasons for a real version installing. Just create an alias `node` for a cached one and keep the disk space. But I guess it’s kind a breaking change. And perhaps I don’t see disadvantages of skipping the real installing. And it’s just thoughts, so never mind.

Also I didn’t get the idea of using `ls-remote`. Doesn’t it just list all available versions? And what should happen after calling `n ls-remote auto`?

And I like the idea of `auto-npm = n exec auto npm`. With this approach and some new label or modified `auto` in my fork I can implement a real multiple installed version behavior I guess. At least I should try.

Thanks for your feedback!

**Comment by shadowspawn** [comment]
What I had in mind was choosing a version of node to run, like:

```bash
#!/bin/bash

auto_node=
auto_node="$(n which auto 2>/dev/null)" || auto_node="$(which node)"

echo "run ${auto_node}"
```

**Comment by artfulsage** [comment]
I will try your suggestion. Thank you and I guess you can close the issue.

**Comment by shadowspawn** [comment]
👍

**Comment by artfulsage** [comment]
Hello again! After a lot of tryings I have got the desired behavior with this script which I imported into my `.zshrc` file:

```bash
#!/bin/bash
n_bin_global=$(which node)

alias n_version_global="$n_bin_global -v"
alias n_version_local="n lsr auto"
alias n_version_detected="(n_version_local 2>/dev/null || n_version_global)"
alias node="n_version_detected | xargs -I {} n run {}"
alias npm="n_version_detected | xargs -I {} n exec {} npm"
```

Now wherever I run `node` or `npm` I use the project-defined version if it’s found or the global one. Looks like not only me is interested in this feature, so I suggest to add it to `README` file (it would be my pleasure) or let it just be here as a comment.

If the called version is not installed I get an error and I think this is how it should be.

related to https://github.com/tj/n/issues/730
