### ISSUE TITLE
Fallback to .gz when .xz is offline

### ISSUE THREAD

**Issue by lbenedix** [tj/n#760]
# Problem

Sometimes https://nodejs.org/dist/v16.19.1/node-v16.19.1-linux-arm64.tar.xz is not available and our builds fails. 
Our workaround is setting `--no-use-xz` but I kind of lost my trust that any of the files is reliably available. 🙃

It would be cool to have `n` to fallback to the tar.gz file in this case.

## Logs

```bash
[Container] 2023/03/16 10:23:16 Running command n 16
installing : node-v16.19.1
curl: (22) The requested URL returned error: 404
Error: download preflight failed for '16.19.1' (https://nodejs.org/dist/v16.19.1/node-v16.19.1-linux-arm64.tar.xz)
[Container] 2023/03/16 10:23:17 Command did not exit successfully n 16 exit status 1
```

## Workaround
```bash
> n install --no-use-xz 16 || n install 16
```

**Comment by moloko** [comment]
Don't know if this helps or not but I came here because I had a very similar issue/error installing v18.15.0 on macOS ARM... despite the URL https://nodejs.org/dist/v18.15.0/node-v18.15.0-darwin-arm64.tar.xz clearly being reachable.

After a few tries to no avail I went to the folder where `n` keeps all the Node versions and saw it contained a subfolder called 18.15.0 with an (empty) file in it called n.lock. I deleted the folder and file then tried installing 18.15.0 again and then it worked fine.

Could have just been coincidence but thought might be worth suggesting as something to try.

**Comment by lbenedix** [comment]
The files are offline and online randomly thoughout the day. Most of the time it's just one that is not available.

```
> curl -I https://nodejs.org/dist/v16.19.1/node-v16.19.1-linux-arm64.tar.gz

HTTP/2 404
date: Thu, 16 Mar 2023 17:13:34 GMT
content-type: text/html
cache-control: max-age=14400
cf-cache-status: HIT
age: 652
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 7a8ea0a8ff08bb59-FRA
```

**Comment by shadowspawn** [comment]
There is an active problem with intermittent 404s affecting downloads:

- https://status.nodejs.org
- https://github.com/nodejs/nodejs.org/issues/5149

**Comment by shadowspawn** [comment]
Is this fixed now? (i.e. by the Node.js fix)

**Comment by shadowspawn** [comment]
In answer to the fallback idea: the current approach when looking for a file to download is to work out an appropriate download based on the local environment (e.g. operating system and machine architecture) and what is declared as available in the index file, and only try one.

I am still ok with this approach. I admit that this is also easier to code and handle errors with just one attempt!

The underlying cause of this issue has been resolved by improvements to Node.js distribution.

**Comment by shadowspawn** [comment]
Thanks for the diagnosis information @lbenedix and @moloko
