### ISSUE TITLE
[Feature Request] Post change version hooks

### ISSUE THREAD

**Issue by samjarman** [tj/n#763]
# Problem

I'd like a hook _or similar_ that would let me run some custom bash code after changing to certain versions. 

Ideally I'd like to write some code like this in my zshrc (pseudo code):

```
n_hook(newVersion) {
    if (newVersion == node 18) {
        // set up some NODE_OPTION flags that only work on node 18
    }
}
```

My exact problem: I need to have these settings for my system to work 
```
export NODE_OPTIONS=--dns-result-order=ipv4first
```

However, when I change between node 18 and 14, then node will error because this option appeared in node 16. 

So I really just want to be able to conditionally set this, and I think I need `n` to help me out here.

---

This feature has quite a few use cases too.

Thoughts very welcome! I just want to get the conversation started.

**Comment by shadowspawn** [comment]
Interesting use case. I suspect this is out of scope for `n`, but not sure how it might be achieved.

The closest existing use case is probably `n exec`. Since `n` is a shell script and not installed into the shell, it can't modify environment variables in the calling shell. So `n exec` sets PATH and starts a new shell to run the specified command.

A high level issue is that changing the installed version of node in one shell can't directly affect the setup in other running shells. So mapping the use case onto `n run` or `n exec` which are one-shot commands probably works better.

I can imagine a wrapper script detecting the target version of node and making changes. Not sure what other mechanisms might work.

**Comment by shadowspawn** [comment]
This issue has not had any activity in a month. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
