### ISSUE TITLE
Failure to remove existing homebrew symlinks?

### ISSUE THREAD

**Issue by clanktron** [tj/n#766]
# Bug Report

## Summary

When changing node versions on macos the `include` and `doc` directories are not overwritten due to them being symlinks to the node version installed by homebrew. I'm aware I can manually remove these symlinks, but is this manual intervention the intended course of action? Could the script link the node version with a `ln -sf` instead of copying it? Or maybe even just check if the existing dir is a symlink, remove it if it is, and then copy as per usual?

## Steps to Reproduce

Install node via brew: `brew install node`
Install n via npm: `npm install -g n`
Change node version: `n 17`

Result:
```bash
     copying : node/17.9.1
cp: cannot overwrite non-directory '/usr/local/include/node' with directory '/usr/local/n/versions/node/17.9.1/include/node'
cp: cannot overwrite non-directory '/usr/local/share/doc/node' with directory '/usr/local/n/versions/node/17.9.1/share/doc/node'
   installed : v17.9.1 (with npm 8.11.0)
```
Also to be clear the node version is switched just fine (`node -v` returns 17.9.1), it's just the above directories.

**Comment by shadowspawn** [comment]
The copying is already "destructured" to cope with certain folders being symlinks in various Linux distributions.

**Comment by shadowspawn** [comment]
Of some relevance, the copying is broken into pieces to cope with various folders being symlinks in various Linux distributions.

https://github.com/tj/n/blob/02a8fe0c540576e0108b4e6f1797f2e71bc3dffc/bin/n#L678

>  is this manual intervention the intended course of action

I would suggest uninstalling node from brew since going to overwrite with `n`.

> Or maybe even just check if the existing dir is a symlink, remove it if it is, and then copy as per usual?

That would be reasonable, except it does not scale up very well. I have experimented in the past with rsync to cope with aliases better, and wondered about doing the recursive copy by hand using `find`, but decided to stick with using `cp` with workarounds.

**Comment by clanktron** [comment]
> I would suggest uninstalling node from brew since going to overwrite with n.
As far as my use case is concerned this seems like a reasonable solution for the issue, so I'm good with closing it if there's no intention on changing existing functionality.
>That would be reasonable, except it does not scale up very well.
Just out of curiosity why is this? Is it that including an `if [ -L dirname ]` before every cp is to cumbersome or is it some other logistical thing?

**Comment by shadowspawn** [comment]
> Just out of curiosity why is this? Is it that including an if [ -L dirname ] before every cp is to cumbersome or is it some other logistical thing?

The problem is the folders nested under the folder being copied. So in your case, there is no explicit copy of `/usr/local/share/doc/node`. To expose that means excluding it from the main copy and adding a separate copy, like has been done for `share/man`.

https://github.com/tj/n/blob/02a8fe0c540576e0108b4e6f1797f2e71bc3dffc/bin/n#LL722C10-L722C10

Historical note: the current approach was added in #657.

**Comment by shadowspawn** [comment]
Since this is fixable by end-user with a reasonable action, I am not planning to add specific support. (Revisit if more of the same or similar issues get reported!)
