### ISSUE TITLE
Installation error. Pls help.

### ISSUE THREAD

**Issue by prathmesh-ka-github** [tj/n#797]
# Problem

I was trying to install n but this err message popped up  
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@9.2.1: wanted {"os":"!win32"} (current: {"os":"win32"})
npm ERR! notsup Valid os:  !win32
npm ERR! notsup Actual os: win32

![image](https://github.com/tj/n/assets/103999608/9669ad33-9b6f-4aff-8bdc-fa693218e0aa)

## command used
```
npm install -g n
```

It is saying "Unsupported platform" win32, but I have a 64 bit Operating System Windows 10.  
How can I configure that? please help.

**Comment by shadowspawn** [comment]
The problem isn't win32 vs win64, although that isn't clear from the error. The problem is Windows. `n` is written as a BASH script and is not usable from a Windows shell.

Have a look at the Supported Platforms section in the README to see if `n` will be useful to you in WSL:
- https://github.com/tj/n#supported-platforms

**Comment by shadowspawn** [comment]
For interest, the `process.platform` field available from NodeJS only has `win32` for "Windows":

https://nodejs.org/docs/latest/api/process.html#processplatform

**Comment by prathmesh-ka-github** [comment]
Okay thanks for helping out. I will set up a WSL.
